export const options = [
  { value: "Karlsruhe", label: "Karlsruhe" },
  { value: "Leimen", label: "Leimen" },
  { value: "Darmstadt", label: "Darmstadt" },
  { value: "Berlin", label: "Berlin" },
  { value: "Munich", label: "Munich" },
  { value: "Leipzig", label: "Leipzig" },
  { value: "Bonn", label: "Bonn" },
  { value: "Hannover", label: "Hannover" },
  { value: "Kassel", label: "Kassel" },
  { value: "Frankfurt am Main", label: "Frankfurt am Main" },
  { value: "Mannheim", label: "Mannheim" },
  { value: "Bremen", label: "Bremen" },
  { value: "Heidelberg", label: "Heidelberg" },
];
export const carTypeOptions = [
  { value: "SUV", label: "SUV" },
  { value: "Sedan", label: "Sedan" },
  { value: "Limousine", label: "Limousine" },
  { value: "Hatchback", label: "Hatchback" },
  { value: "Convertible", label: "Convertible" },
  { value: "Wagon", label: "Wagon" },
  { value: "Coupe", label: "Coupe" },
  { value: "Muscle", label: "Muscle" },
];
